# Upon commit and PR run python .github/workflows/utils/make.py build_all
# to check if all examples compile
# Install fortran compiler

name: Test Compilation

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Fortran compiler
        run: sudo apt-get install gfortran
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/utils/requirements.txt
      - name: Build all
        run: python .github/workflows/utils/make.py build_all
